
import Head from 'next/head'
import Auth from '../components/Auth'
import styles from '../styles/Home.module.css'

import { useState, useEffect } from 'react'
import { supabase } from '../services/db'
import { Session } from '@supabase/supabase-js'
import Account from '../components/Account'


export default function Home() {
  const [isLoading, setIsLoading] = useState(true)
  const [session, setSession] = useState(null as Session | null)

  useEffect(() => {
    let mounted = true

    async function getInitialSession() {
      const {
        data: { session },
      } = await supabase.auth.getSession()

      // only update the react state if the component is still mounted
      if (mounted) {
        if (session) {
          setSession(session)
        }

        setIsLoading(false)
      }
    }

    getInitialSession()

    const { data } = supabase.auth.onAuthStateChange(
      (_event, session) => {
        setSession(session)
      }
    )
    const subscription = data.subscription

    return () => {
      mounted = false

      subscription?.unsubscribe()
    }
  }, [])

  return (
    
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
      <Head>
        <title>Backpage Pass</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {!session ? ( 
        <>
          <h1 className={styles.title}>
          Welcome Backpage Pass!
          </h1>
          <p className={styles.description}>
            Let your customers sign in to your site with an NFT!
          </p>
          <Auth></Auth>
        </>
      ) : (
        <div>
          <h1>Welcome! {session.user.id}</h1>
        </div>
      )}
      </main>
    </div>
  )
}
